name: Python Code Check

on:
  workflow_dispatch: # Manually trigger the workflow
  pull_request:
  push:


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: pip install flake8

    - name: Run Flake8 Linter
      run: flake8 --exclude=__init__.py .

    - name: Check for Errors
      run: |
        if [ $? -eq 0 ]; then
          echo "No issues found. Push is allowed."
        else
          echo "Code has issues. Please fix them before pushing."
          exit 1
